### ISSUE TITLE
Feature Request: Python CLI Tool

### ISSUE THREAD

**Issue by xloem** [NebulousLabs/python-skynet#13]
This would ease testing the library and provide multiple options in addition to the nodejs tool, for users of edge-case systems.

**Comment by m-cat** [comment]
Are you aware of our new project https://github.com/NebulousLabs/skynet-cli? Does it satisfy your needs?

**Comment by m-cat** [comment]
Closing as we won't be creating another CLI tool at this time.

**Comment by xloem** [comment]
Thanks for closing this.  I think is a less accessible language than python, but when I opened this I think I was planning on contributing the client for test cases, and I never had time for this.
