### ISSUE TITLE
It will be helpful if app developer gets an option to overwrite "default options" in sdk

### ISSUE THREAD

**Issue by jjchauhan** [NebulousLabs/python-skynet#2]
It will be helpful if app developer gets an option to overwrite "default portal endpoint" in sdk
            '': 'https://siasky.net',
            'portalUploadPath' : '/api/skyfile',
            'portalFileFieldname' : 'file',
            'customFilename':''

**Comment by peterjanbrone** [comment]
I believe you have this option already. It's just a default param 
`def UploadFile(path, opts=None):` but you can pass in your own options if you want.
Please close this issue if this is sufficient for your requirements.

**Comment by jjchauhan** [comment]
Tested with latest SiaSkynet package and it worked fine.thanks you PJ
