### ISSUE TITLE
Tests pretend to verify content access

### ISSUE THREAD

**Issue by xloem** [NebulousLabs/python-skynet#37]
The upload tests take the energy to verify the returned skylink ( https://github.com/NebulousLabs/python-skynet/blob/021e45ffac266e3e2a1f8dcee7b214836a3e3faa/tests/test_integration_upload.py#L33 ) but they themselves provide this skylink ( https://github.com/NebulousLabs/python-skynet/blob/021e45ffac266e3e2a1f8dcee7b214836a3e3faa/tests/test_integration_upload.py#L27 ).  They seem to be simply testing the mocking `responses` library at this point.  It seems a little dangerous as it could seem like it is testing more than it really is, to casual review.

**Comment by xloem** [comment]
I'm sorry for this.  I am so confused.  I'm just trying to migrate my software to the new API.

**Comment by m-cat** [comment]
No problem @xloem , I totally understand that this is a little confusing. We are only using mocks and not full integration tests, which would be expensive. All we check is that the requests are formed correctly, but this style of testing is not perfect.
