### ISSUE TITLE
Assertion Error: in _upload.py 

### ISSUE THREAD

**Issue by cycleworm** [NebulousLabs/python-skynet#43]
i think there is some problem in the upload_directory function. 

i tried to run a simple example
![pic1](https://user-images.githubusercontent.com/493769/102268127-30c7cf00-3f1b-11eb-92aa-75a95dde630b.png)

it gives me an AssertionError (pic2)
![pic2](https://user-images.githubusercontent.com/493769/102268128-31f8fc00-3f1b-11eb-910b-57293004805a.png)

if i comment out line 195 in the _upload.py the upload works without any errors. 

but still something is wrong with the folder and file structure. for example a index.html cannot
correctly load a file in css/style.css

If i upload the same folder with the siasky.net webportal the files are linked correctly.

**Comment by m-cat** [comment]
What is your OS @cycleworm ?

**Comment by cycleworm** [comment]
Windows 10 64 Bit
Version 20H2 (OS Build 19042.685)

when commenting out the mentioned line i saw that files got uploaded. files are there but they are empty.
Only the index.html has data in it.

**Comment by m-cat** [comment]
Hey @cycleworm , I'm having trouble getting it to run on Windows at all. I think it's for this reason that we haven't really supported Windows before, and we don't test Windows in our CI suite.

I would definitely need a Python expert's (or Windows users's) help in getting it to run on Windows . Are you able to run e.g. `pipenv run test` btw?

**Comment by cycleworm** [comment]
Hey @m-cat.
yes i can run `pipenv run test` after installing it with `pip install pipenv`

![Screenshot_3](https://user-images.githubusercontent.com/493769/102403536-b2d0fa00-3fe6-11eb-8e10-e81dbed8e77b.png)

What exactly have you tried?

**Comment by m-cat** [comment]
Fixed in https://github.com/NebulousLabs/python-skynet/pull/44. Sounds like there's still an issue with uploading directories which I'll take a look at. After that I'll release a new version of the SDK.
